void reset_to_98(int *x);
void swap_int(int *a, int *b);
int _strlen(char *str);
void _puts(char *c);
int _putchar(char *s);
void print_rev(char *str);
void puts2(char *str);
void puts_half(char *str);
void print_array(int *a, int x);
char *_strcpy(char *dest, char *src);
void rev_string(char *x);
